### ISSUE TITLE
can we use .rdb ?

### ISSUE THREAD

**Issue by daydaygo** [hhxsv5/go-redis-memory-analysis#2]
i can not use the tool in production environment, but i can get .rdb file, can the tool support .rdb file ?

**Comment by hhxsv5** [comment]
Sorry, I have no plan to analyze rdb file.
You can try [sripathikrishnan/redis-rdb-tools](https://github.com/sripathikrishnan/redis-rdb-tools).

**Comment by hhxsv5** [comment]
I found this library [vrischmann/rdbtools](https://github.com/vrischmann/rdbtools), but cannot work out  the usage of size.

**Comment by hhxsv5** [comment]
Enjoy ! [v2.0.6](https://github.com/hhxsv5/go-redis-memory-analysis/releases/tag/v2.0.6)
