### ISSUE TITLE
最新的 windows release 二进制压缩包内不是 .exe 文件，需要自己手动改后缀名

### ISSUE THREAD

**Issue by waconde** [hhxsv5/go-redis-memory-analysis#7]
解压后发现是个无后缀名的文件，windows 不认识，得自己手动修改后缀名为 .exe。然后在 cmd 命令行中可以正常使用：
redis-memory-analysis-windows-amd64.exe -h
……

**Comment by hhxsv5** [comment]
已更新 https://github.com/hhxsv5/go-redis-memory-analysis/releases/tag/v2.0.6
